title: "찌니노트"
description: "프로그래밍, 그리고 이것저것"
permalink: post/:title
url: https://zininote.github.io
tag_order: [algorithm]

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true
